# Generated by Django 4.0 on 2023-02-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_rename_genge_game_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="stripe_game_price_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
