# Generated by Django 4.0 on 2023-02-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_stripe_game_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True, verbose_name='URL'),
        ),
    ]
